// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240111.5

#pragma once
#ifndef WINRT_CaptureEncoderWin32_2_H
#define WINRT_CaptureEncoderWin32_2_H
#include "winrt/impl/CaptureEncoderWin32.1.h"
WINRT_EXPORT namespace winrt::CaptureEncoderWin32
{
    struct WINRT_IMPL_EMPTY_BASES Class : winrt::CaptureEncoderWin32::IClass
    {
        Class(std::nullptr_t) noexcept {}
        Class(void* ptr, take_ownership_from_abi_t) noexcept : winrt::CaptureEncoderWin32::IClass(ptr, take_ownership_from_abi) {}
        Class();
    };
}
#endif
