// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240111.5

void* winrt_make_CaptureEncoderWin32_Class()
{
    return winrt::detach_abi(winrt::make<winrt::CaptureEncoderWin32::factory_implementation::Class>());
}
WINRT_EXPORT namespace winrt::CaptureEncoderWin32
{
    Class::Class() :
        Class(make<CaptureEncoderWin32::implementation::Class>())
    {
    }
}
